#area-azure:

area-blazor:
  - src/Components/**/*

#area-commandlinetools:

area-dataprotection:
  - src/DataProtection/**/*

#area-grpc:

#area-healthchecks:

area-hosting:
  - src/Hosting/**/*
  - src/SiteExtensions/**/*

#area-httpclientfactory:

area-identity:
  - src/Identity/**/*

area-infrastructure:
  - global.json
  - .azure/**/*
  - .config/**/*
  - eng/**/*

area-installers:
  - src/Installers/**/*

area-middleware:
  - src/Middleware/**/*

area-mvc:
  - src/ProjectTemplates/**/*
  - src/Razor/**/*
  - src/Mvc/**/*
  - src/MusicStore/**/*
  
#area-platform:

area-security:
  - src/Security/**/*

area-servers:
  - src/Servers/**/*

area-signalr:
  - src/SignalR/**/*

#area-websockets:

api-suggestion:
  - src/**/ref/**/*
